name: mission_planer
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  collection: ^1.18.0
  dart_jts: ^0.3.0+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.1
  flutter_map_dragmarker: ^7.0.0

  intl: ^0.19.0
  latlong2: ^0.9.1
  meta: ^1.15.0
  talker: ^4.4.1
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  logger: ^2.4.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
